#if defined(FORDBOARD)

#elif defined(CROSSCHASM_C5_BT)

#elif defined(CHIPKIT)

#elif defined(CROSSCHASM_C5_CELLULAR)

    #define TELIT_HE910_SUPPORT

    #define TELIT_HE910_ENABLE_SUPPORT

    #define TELIT_HE910_ENABLE_PIN_POLARITY 1
    #define TELIT_HE910_ENABLE_PORT 0
    #define TELIT_HE910_ENABLE_PIN 32 // PORTE BIT5 (RE5)

#endif
