TARGET       = cantranslator
BOARD_TAG    = mega_pic32

ARDUINO_LIBS = chipKITCAN chipKITUSBDevice chipKITUSBDevice/utility

ifndef ARDUINO_PORT
ARDUINO_PORT = /dev/ttyUSB*
endif

include $(ARDUINO_MAKEFILE_HOME)/chipKIT.mk
