# This is a basic workflow to help you get started with Actions

name: Run Tests

# Controls when the action will run. 
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # Runs a single command using the runners shell
      - name: Set Up Python 3.6
        run: |
          TERM=xterm
          sudo apt-get update -qq
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get update -qq
          sudo apt-get install python3.6 -y
          sudo rm /usr/bin/python3
          sudo ln -s /usr/bin/python3.6 /usr/bin/python3
          wget https://bootstrap.pypa.io/get-pip.py
          sudo python3 get-pip.py
          sudo apt-get install -qq -y libsubunit-dev
          sudo apt-get install python-apt
          sudo apt-get install python3-apt

      # Runs a single command using the runners shell
      - name: Bootstrap
        run: |
          script/bootstrap.sh
          
      - name: Build Tests
        run: |
          cd src
          PLATFORM=TESTING make test

          
